<?php namespace JF;
/**

Copyright 2023 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-3b261c
Date:    2023-08-02 08:07:14
Version: v2023.2.15
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

date_default_timezone_set( 'America/New_York' );

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-3b261c",
    "email": {
        "to": "booking.nailprojects@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "Nail Project - Appointment Form",
        "template": "Please note that your appointment will only be confirmed if you received a text from us. If you didn\u2019t received or hear from us that mean the time slot you chose isn\u2019t available. Please call us before going in. Thank you!",
        "fromName": "Nail Projects",
        "sendmail_from": "booking.nailprojects@gmail.com"
    },
    "admin": {
        "users": "admin:a17a3bc1f3",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "Please note that your appointment will only be confirmed if you received a text from us. If you didn\u2019t received or hear from us that mean the time slot you chose isn\u2019t available. Please call us before going in. Thank you!",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": false,
        "subject": "Thanks For Booking",
        "template": "Thank you for choosing Nail Projects! We appreciate your interest in our services and the time you've taken to fill out our booking form.\n\nThis email is to acknowledge that we have received your booking request. Our team is currently reviewing the details you provided and will work diligently to ensure that all your preferences are taken into account.\n\nWe will be in touch with you shortly to discuss the availability, finalize the details, and confirm your booking. Your satisfaction is our priority, and we want to ensure that everything is perfectly tailored to your needs.\n\nIf you have any immediate questions or concerns, please do not hesitate to contact our customer service team at 917.909.0142. We're here to assist you and provide any information you may require.\n\nOnce again, thank you for considering Nail Projects. We look forward to the opportunity to serve you and make your upcoming experience a memorable one.\n\nBest Regards,\nNail Projects\nA: 138 7th Avenue. Brooklyn, NY 11215\nE: nailprojectny@gmail.com\nW: nailprojects.com"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "smtp.gmail.com",
        "user": "booking.nailprojects@gmail.com",
        "password": "kat030308",
        "port": "465",
        "security": "ssl"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "red"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "First Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "firstname",
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "minlength": {
                        "enabled": false
                    },
                    "equalto": {
                        "enabled": false
                    }
                }
            },
            "id": "f4",
            "cid": "c27"
        },
        {
            "label": "Last Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "lastname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f5",
            "cid": "c32"
        },
        {
            "label": "Email",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f6",
            "cid": "c39"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    },
                    "phonenumber": {
                        "enabled": false
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f7",
            "cid": "c44"
        },
        {
            "label": "Select Services",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Manicure",
                        "checked": false
                    },
                    {
                        "label": "Pedicure",
                        "checked": false
                    },
                    {
                        "label": "Spa Pedicure",
                        "checked": false
                    },
                    {
                        "label": "Waxing",
                        "checked": null
                    },
                    {
                        "label": "Massage",
                        "checked": null
                    },
                    {
                        "label": null,
                        "checked": null
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": ""
            },
            "id": "f17",
            "cid": "c61"
        },
        {
            "label": "Open Hours",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "mainDescription": "Mon-Sat: 10:00am-8:00pm Sunday: 10:00am-7:00pm"
            },
            "id": "f11",
            "cid": "c68"
        },
        {
            "label": "Appointment Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f12",
            "cid": "c73"
        },
        {
            "label": "Appointment Time",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f13",
            "cid": "c78"
        },
        {
            "label": "Numbers of Guests",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f14",
            "cid": "c83"
        },
        {
            "label": "Message",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "validators": {
                    "required": {
                        "enabled": false
                    }
                }
            },
            "id": "f15",
            "cid": "c88"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": "",
    "twilio": {
        "toPhone": ""
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class