<?php namespace JF;
/**

Copyright 2023 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-3637fe
Date:    2023-06-05 10:10:19
Version: v2023.2.15
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

date_default_timezone_set( 'America/New_York' );

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-3637fe",
    "email": {
        "to": "amstudio.usa@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "New Appointment Details for Nail Project",
        "template": "You receive an email from {sender.fullname}.\n\nThe web form data:\n{dataTable}\n\n\nDate: {Date}\nTime: {Time}\nWebsite: {HTTP_HOST}\nReferer: {HTTP_REFERER}\n",
        "fromName": "Nail Project"
    },
    "admin": {
        "users": "admin:2c6bee9719",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "Please note that your appointment will only be confirmed if you received a text from us. If you didn\u2019t received or hear from us that mean the time slot you chose isn\u2019t available. Please call us before going in. Thank you!",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "Thanks for your appoinment!",
        "template": "Dear {sender.fullname},\n\nThank you for filling out the form. Here is the copy of your data:\n{dataTable}\n\nPlease note that you are requesting an appointment not actually booking an appointment. Your request has to be first approved by a member of our team. If you are making a request during our hours of operation your request will be processed within a few hours. If you are making a request during our non operating hours then your request will be processed the next day in which we are open by 10am. Please be sure to check your email for appointment approval or appointment denial. If you are requesting an appointment within 24 hours please call our salon directly at 917.909.0142.\n\nBest Regards,\n{HTTP_HOST}\n\nYour IP: {IP}\nDate: {Date}\nTime: {Time}\n"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "red"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "First Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "firstname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f7",
            "cid": "c43"
        },
        {
            "label": "Last Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "lastname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f8",
            "cid": "c48"
        },
        {
            "label": "Email",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f9",
            "cid": "c53"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f18",
            "cid": "c101"
        },
        {
            "label": "Select Services",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Manicure",
                        "checked": false,
                        "value": ""
                    },
                    {
                        "label": "Pedicure",
                        "checked": false
                    },
                    {
                        "label": "Spa Pedicure",
                        "checked": false
                    },
                    {
                        "label": "Waxing",
                        "checked": null
                    },
                    {
                        "label": "Massage",
                        "checked": null
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f10",
            "cid": "c58"
        },
        {
            "label": "Open Hours",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "mainDescription": "Mon-Sat: 10:00am-8:00pm Sunday: 10:00am-7:00pm"
            },
            "id": "f11",
            "cid": "c64"
        },
        {
            "label": "Appointment Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f12",
            "cid": "c69"
        },
        {
            "label": "Appintment Time",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f14",
            "cid": "c79"
        },
        {
            "label": "Numbers of Guests",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f15",
            "cid": "c84"
        },
        {
            "label": "Message",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f17",
            "cid": "c94"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class