<?php namespace JF;
/**

Copyright 2022 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-44aa3c
Date:    2022-05-06 13:49:24
Version: v3.1
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-44aa3c",
    "email": {
        "to": "amstudio.usa@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "Reservation Form",
        "template": "You receive an email from {sender.fullname}.\n\nThe web form data:\n{dataTable}\n\nReference ID: {AutoID}\nIP: {IP}\nDate: {Date}\nTime: {Time}\nWebsite: {HTTP_HOST}\n",
        "fromName": "Nail Projects"
    },
    "admin": {
        "users": "admin:15cd413e91",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "Your booking has been sent successfully. This is not a confirmed booking, you will receive an email regarding availability and confirmation of your booking.\n\nPlease call us if you have not heard from us within an hour (during opening hours) as our email system may be down. We\u2019d love to the opportunity to serve you.\n\nIf you do not receive the acknowledgement email within a few minutes of your booking, please check your Junk\/Spam E-mail folder, just in case the email got delivered there instead of your inbox. If so, the confirmation email will probably be delivered to your Junk\/Spam folder as well.",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "Thank you for booking with Nail Project!",
        "template": "Dear {sender.fullname},\n\nThank you for booking an appointment! It truly helps us properly staff our days and make sure we keep everything moving in a timely manner! Here is the copy of your reservation details:\n{dataTable}\n\nThis is not a confirmed booking, you will receive an email regarding availability and confirmation of your booking.\n\nPlease call us if you have not heard from us within an hour (during opening hours) as our email system may be down. We\u2019d love to the opportunity to serve you.\n\nIf you do not receive the acknowledgement email within a few minutes of your booking, please check your Junk\/Spam E-mail folder, just in case the email got delivered there instead of your inbox. If so, the confirmation email will probably be delivered to your Junk\/Spam folder as well.\n\nBest Regards,\n{HTTP_HOST}\n\n"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "First Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "firstname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Last Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "lastname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f5",
            "cid": "c33"
        },
        {
            "label": "Email Address",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f6",
            "cid": "c39"
        },
        {
            "label": "Contact Number",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f7",
            "cid": "c44"
        },
        {
            "label": " Booking Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "date": {
                    "startDate": "0d"
                }
            },
            "id": "f8",
            "cid": "c49"
        },
        {
            "label": "Booking Time",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Mon-Sat: 10:00am-8:00pm \/ Sunday: 10:00am-7:00pm -",
                        "value": "#novalue",
                        "checked": true
                    },
                    {
                        "label": "10:00 am",
                        "checked": false
                    },
                    {
                        "label": "10:15 am",
                        "checked": false
                    },
                    {
                        "label": "10:30 am",
                        "checked": false
                    },
                    {
                        "label": "10:45 am",
                        "value": null,
                        "checked": false
                    },
                    {
                        "label": "11:00 am",
                        "value": null,
                        "checked": false
                    },
                    {
                        "label": "11:15 am",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "11:30 am",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "11:45 am",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "12:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "12:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "12:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "12:45 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "01:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "01:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "01:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "01:45 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "02:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "02:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "02:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "02:45 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "03:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "03:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "03:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "03:45 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "04:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "04:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "04:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "04:45 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "05:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "05:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "05:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "05:45 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "06:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "06:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "06:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "06:45 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "07:00 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "07:15 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "07:30 pm",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "07:45 pm",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f13",
            "cid": "c81"
        },
        {
            "label": "Comments",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f14",
            "cid": "c37"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class